apiVersion: v1
kind: ConfigMap
metadata:
  name: vod-video-service-configmap
  namespace: vod
data:
  connection_string: "mongodb://root:****@mongodb-standalone.mongodb.svc.calfolguera.com:27017/vod-video-service?authSource=admin"
