apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-video-service-deployment
  namespace: vod
  labels:
    app: vod-video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vod-video-service
  template:
    metadata:
      labels:
        app: vod-video-service
    spec:
      containers:
        - name: vod-video-service
          image: hfolguera/vod-video-service:1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 2000
          env:
            - name: MONGODB_URL
              valueFrom:
                  configMapKeyRef:
                    name: vod-video-service-configmap
                    key: connection_string
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: pass