name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

#  test:
#  
#    runs-on: ubuntu-latest
#    
#    - name: NPM test
#      ??

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Get NPM Application version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vod-video-service:${{ steps.package-version.outputs.current-version}},latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
    - name: Docker logout
      run: docker logout
